### ISSUE TITLE
Unconfigured Items are Deleted

### ISSUE THREAD

**Issue by IAmSneak** [OverlordsIII/ConfiguredKeepInventory#2]
Items that are not in the keepInventory list are completely deleted instead of being dropped on the ground.

**Comment by OverlordsIII** [comment]
I can’t get my n the computer rn so I’ll look at it tmrw. Seems strange tho this wasn’t happening in dev env. What is your config drop rate? That may be related

**Comment by OverlordsIII** [comment]
I’ll look at it tho

**Comment by IAmSneak** [comment]
[inventory.txt](https://github.com/OverlordsIII/ConfiguredKeepInventory/files/5322752/inventory.txt)

**Comment by OverlordsIII** [comment]
I couldn't get this bug in a development environment, but I have redone all the code related to inventory management. I'm going to release it, and it might fix your issue.

**Comment by OverlordsIII** [comment]
Ok Released it

**Comment by OverlordsIII** [comment]
ok its approved try using it and seeing if the problem is still there

**Comment by IAmSneak** [comment]
The problem is still there. The items that are supposed to be kept after death are now dropped on the ground as well.

**Comment by OverlordsIII** [comment]
[This is what is happening for me at 90% droprate](https://streamable.com/)

**Comment by IAmSneak** [comment]
Maybe try downloading [the config] (https://github.com/OverlordsIII/ConfiguredKeepInventory/files/5324668/inventory.txt)? Don't forget to change .txt to .json5. I had 1 shulker box and 2 cooked porkchops in my inventory before dying to fall damage.

**Comment by IAmSneak** [comment]
Wait am I supposed to have gamerule keepInventory set to true?

**Comment by OverlordsIII** [comment]
no u shouldnt have to
i gtg but ill come back in 30 mins

**Comment by OverlordsIII** [comment]
If you have 1 shulker box and 2 cooked porkchops, the mod will calculate based on the stack size, so since you have it at 90 which is really high, and a small stack size the [mod will round up](https://github.com/OverlordsIII/ConfiguredKeepInventory/blob/master/src/main/java/io/github/overlordsiii/mixin/PlayerInventoryMixin.java#L61-L62). This means it would drop everything on the ground. Try having a stack of items and see if it works or not.

**Comment by OverlordsIII** [comment]
If you think it should be different and round down instead
i can try to add that as a config option

**Comment by IAmSneak** [comment]
Well the problem I have is that the items are completely deleted, not dropped. In the most recent update the shulker boxes should be kept while the other items drop on the floor, but instead the shulker boxes drop on the floor and the other items are deleted as if they had curse of vanishing.

**Comment by OverlordsIII** [comment]
Attempt 2 electric boogaloo: download the [latest jar](https://www.curseforge.com/minecraft/mc-mods/configured-keep-inventory/files/all) and go to the config and set roundUp to false, save it,  and try again and see if it works or not

**Comment by IAmSneak** [comment]
Looks like it works as expected with roundUp set to false. Is this expected behavior though? 
[Video](https://streamable.com/az5n8o)
[latest.log](https://github.com/OverlordsIII/ConfiguredKeepInventory/files/5329439/latest.log)

**Comment by OverlordsIII** [comment]
ok the log shouldnt be spammed like that lemme fix that

**Comment by IAmSneak** [comment]
At 14:40:46 in the logs it says "Copy Stack = 2 air" when it should be 2 oxeye_daisy. Is it dropping air instead of the stack?

**Comment by OverlordsIII** [comment]
yea that seems to be what is happening and from your video it seems that is only a problem with roundup set to true

**Comment by OverlordsIII** [comment]
Ok i think i fixed it 🤞 uploading it to curseforge

**Comment by OverlordsIII** [comment]
Ok its uploaded check it out and see if it works or not

**Comment by IAmSneak** [comment]
Sorry, thought I responded. It seems to work in both cases now, nice job!

**Comment by OverlordsIII** [comment]
Thanks, you gave me a lot of good info too for me to help
