### ISSUE TITLE
Crash on new map creation(conflicts with carpet mod)

### ISSUE THREAD

**Issue by NightOps007** [OverlordsIII/ConfiguredKeepInventory#3]
Also posted to carpet team: [#515](https://github.com/gnembon/fabric-carpet/issues/515). Please check the link for more details.

**Comment by OverlordsIII** [comment]
Hmm you might be using a slightly outdated version of ConfiguredKeepInventory. The crash that is happening is related to me accidently leaving a feature with how carpet outputs its command stacktrace. I'll release a new jar without this change if you have the latest version (1.1.1).

**Comment by OverlordsIII** [comment]
Wait never mind I saw your mods list. It's a problem on my end will fix soon

**Comment by OverlordsIII** [comment]
Ok i've submitted it to curseforge just get the latest release there. Tell me if it works or if it still crashes again.

**Comment by NightOps007** [comment]
Tried it out, works. Thanks for fixing.
